// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xencdec.h"

extern XEncdec_Config XEncdec_ConfigTable[];

XEncdec_Config *XEncdec_LookupConfig(u16 DeviceId) {
	XEncdec_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XENCDEC_NUM_INSTANCES; Index++) {
		if (XEncdec_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEncdec_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEncdec_Initialize(XEncdec *InstancePtr, u16 DeviceId) {
	XEncdec_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEncdec_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEncdec_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

