// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module shift_lfsr (
        ap_ready,
        lfsr_read,
        polymonial_mask,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [31:0] lfsr_read;
input  [31:0] polymonial_mask;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

wire   [30:0] tmp_fu_36_p4;
wire   [0:0] feedback_fu_32_p1;
wire   [31:0] tmp_2_fu_50_p3;
wire   [31:0] tmp_1_fu_46_p1;
wire   [31:0] lfsr_write_assign_fu_58_p2;

assign ap_ready = 1'b1;

assign ap_return_0 = lfsr_write_assign_fu_58_p2;

assign ap_return_1 = lfsr_write_assign_fu_58_p2;

assign feedback_fu_32_p1 = lfsr_read[0:0];

assign lfsr_write_assign_fu_58_p2 = (tmp_2_fu_50_p3 ^ tmp_1_fu_46_p1);

assign tmp_1_fu_46_p1 = tmp_fu_36_p4;

assign tmp_2_fu_50_p3 = ((feedback_fu_32_p1[0:0] === 1'b1) ? polymonial_mask : 32'd0);

assign tmp_fu_36_p4 = {{lfsr_read[31:1]}};

endmodule //shift_lfsr
