-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity knuth_yao_single_WhU_rom is 
    generic(
             dwidth     : integer := 1; 
             awidth     : integer := 7; 
             mem_size    : integer := 109
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of knuth_yao_single_WhU_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 4=> "0", 5 to 6=> "1", 7 to 9=> "0", 10 to 11=> "1", 12 => "0", 13 => "1", 14 => "0", 
    15 => "1", 16 => "0", 17 to 18=> "1", 19 to 21=> "0", 22 => "1", 23 to 27=> "0", 28 => "1", 
    29 to 32=> "0", 33 => "1", 34 to 35=> "0", 36 to 38=> "1", 39 => "0", 40 => "1", 41 to 42=> "0", 
    43 => "1", 44 => "0", 45 to 50=> "1", 51 to 52=> "0", 53 to 55=> "1", 56 to 57=> "0", 58 => "1", 
    59 to 61=> "0", 62 => "1", 63 to 65=> "0", 66 => "1", 67 => "0", 68 to 70=> "1", 71 => "0", 
    72 to 75=> "1", 76 => "0", 77 => "1", 78 => "0", 79 to 80=> "1", 81 to 82=> "0", 83 => "1", 
    84 => "0", 85 to 87=> "1", 88 => "0", 89 => "1", 90 => "0", 91 to 94=> "1", 95 => "0", 
    96 to 98=> "1", 99 to 100=> "0", 101 => "1", 102 to 103=> "0", 104 => "1", 105 => "0", 106 to 107=> "1", 
    108 => "0" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity knuth_yao_single_WhU is
    generic (
        DataWidth : INTEGER := 1;
        AddressRange : INTEGER := 109;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of knuth_yao_single_WhU is
    component knuth_yao_single_WhU_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    knuth_yao_single_WhU_rom_U :  component knuth_yao_single_WhU_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


