-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity knuth_yao_single_VhK_rom is 
    generic(
             dwidth     : integer := 1; 
             awidth     : integer := 7; 
             mem_size    : integer := 109
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of knuth_yao_single_VhK_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 5=> "0", 6 to 10=> "1", 11 to 12=> "0", 13 => "1", 14 => "0", 15 to 16=> "1", 17 to 19=> "0", 
    20 => "1", 21 to 22=> "0", 23 => "1", 24 => "0", 25 to 27=> "1", 28 => "0", 29 => "1", 
    30 => "0", 31 => "1", 32 => "0", 33 => "1", 34 => "0", 35 to 36=> "1", 37 => "0", 
    38 to 39=> "1", 40 to 41=> "0", 42 => "1", 43 => "0", 44 to 45=> "1", 46 to 48=> "0", 49 => "1", 
    50 => "0", 51 => "1", 52 to 54=> "0", 55 => "1", 56 to 59=> "0", 60 => "1", 61 => "0", 
    62 to 67=> "1", 68 => "0", 69 => "1", 70 to 73=> "0", 74 => "1", 75 => "0", 76 to 77=> "1", 
    78 to 80=> "0", 81 to 82=> "1", 83 => "0", 84 to 85=> "1", 86 => "0", 87 to 89=> "1", 90 to 93=> "0", 
    94 to 95=> "1", 96 to 97=> "0", 98 => "1", 99 to 105=> "0", 106 to 108=> "1" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity knuth_yao_single_VhK is
    generic (
        DataWidth : INTEGER := 1;
        AddressRange : INTEGER := 109;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of knuth_yao_single_VhK is
    component knuth_yao_single_VhK_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    knuth_yao_single_VhK_rom_U :  component knuth_yao_single_VhK_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


