-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity knuth_yao_single_QgW_rom is 
    generic(
             dwidth     : integer := 1; 
             awidth     : integer := 7; 
             mem_size    : integer := 109
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of knuth_yao_single_QgW_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 9=> "0", 10 => "1", 11 => "0", 12 to 14=> "1", 15 => "0", 16 => "1", 17 to 19=> "0", 
    20 to 23=> "1", 24 => "0", 25 => "1", 26 to 27=> "0", 28 to 29=> "1", 30 => "0", 31 => "1", 
    32 => "0", 33 => "1", 34 to 36=> "0", 37 to 39=> "1", 40 to 41=> "0", 42 => "1", 43 => "0", 
    44 to 48=> "1", 49 => "0", 50 to 51=> "1", 52 => "0", 53 => "1", 54 => "0", 55 to 56=> "1", 
    57 => "0", 58 to 60=> "1", 61 => "0", 62 => "1", 63 => "0", 64 => "1", 65 to 69=> "0", 
    70 => "1", 71 => "0", 72 => "1", 73 to 79=> "0", 80 to 81=> "1", 82 => "0", 83 to 84=> "1", 
    85 to 87=> "0", 88 => "1", 89 to 93=> "0", 94 to 95=> "1", 96 to 101=> "0", 102 => "1", 103 => "0", 
    104 to 105=> "1", 106 => "0", 107 => "1", 108 => "0" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity knuth_yao_single_QgW is
    generic (
        DataWidth : INTEGER := 1;
        AddressRange : INTEGER := 109;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of knuth_yao_single_QgW is
    component knuth_yao_single_QgW_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    knuth_yao_single_QgW_rom_U :  component knuth_yao_single_QgW_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


