-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shift_lfsr is
port (
    ap_ready : OUT STD_LOGIC;
    lfsr_read : IN STD_LOGIC_VECTOR (31 downto 0);
    polymonial_mask : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of shift_lfsr is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_36_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal feedback_fu_32_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_50_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_46_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lfsr_write_assign_fu_58_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= lfsr_write_assign_fu_58_p2;
    ap_return_1 <= lfsr_write_assign_fu_58_p2;
    feedback_fu_32_p1 <= lfsr_read(1 - 1 downto 0);
    lfsr_write_assign_fu_58_p2 <= (tmp_2_fu_50_p3 xor tmp_1_fu_46_p1);
    tmp_1_fu_46_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_36_p4),32));
    tmp_2_fu_50_p3 <= 
        polymonial_mask when (feedback_fu_32_p1(0) = '1') else 
        ap_const_lv32_0;
    tmp_fu_36_p4 <= lfsr_read(31 downto 1);
end behav;
