// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xencdec.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEncdec_CfgInitialize(XEncdec *InstancePtr, XEncdec_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->S_axi_bundle_BaseAddress = ConfigPtr->S_axi_bundle_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEncdec_Start(XEncdec *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL) & 0x80;
    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEncdec_IsDone(XEncdec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEncdec_IsIdle(XEncdec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEncdec_IsReady(XEncdec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEncdec_EnableAutoRestart(XEncdec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL, 0x80);
}

void XEncdec_DisableAutoRestart(XEncdec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_AP_CTRL, 0);
}

void XEncdec_Set_arr(XEncdec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_ARR_DATA, Data);
}

u32 XEncdec_Get_arr(XEncdec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_ARR_DATA);
    return Data;
}

u32 XEncdec_Get_a_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE);
}

u32 XEncdec_Get_a_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH);
}

u32 XEncdec_Get_a_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + 1);
}

u32 XEncdec_Get_a_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_A;
}

u32 XEncdec_Get_a_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_A;
}

u32 XEncdec_Write_a_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_a_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_a_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_a_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_A_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_A_BASE + offset + i);
    }
    return length;
}

u32 XEncdec_Get_c1_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE);
}

u32 XEncdec_Get_c1_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH);
}

u32 XEncdec_Get_c1_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + 1);
}

u32 XEncdec_Get_c1_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_C1;
}

u32 XEncdec_Get_c1_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_C1;
}

u32 XEncdec_Write_c1_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_c1_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_c1_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_c1_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C1_BASE + offset + i);
    }
    return length;
}

u32 XEncdec_Get_c2_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE);
}

u32 XEncdec_Get_c2_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH);
}

u32 XEncdec_Get_c2_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + 1);
}

u32 XEncdec_Get_c2_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_C2;
}

u32 XEncdec_Get_c2_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_C2;
}

u32 XEncdec_Write_c2_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_c2_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_c2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_c2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_C2_BASE + offset + i);
    }
    return length;
}

u32 XEncdec_Get_m_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE);
}

u32 XEncdec_Get_m_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH);
}

u32 XEncdec_Get_m_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + 1);
}

u32 XEncdec_Get_m_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_M;
}

u32 XEncdec_Get_m_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_M;
}

u32 XEncdec_Write_m_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_m_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_m_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_m_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_M_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_M_BASE + offset + i);
    }
    return length;
}

u32 XEncdec_Get_p_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE);
}

u32 XEncdec_Get_p_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH);
}

u32 XEncdec_Get_p_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + 1);
}

u32 XEncdec_Get_p_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_P;
}

u32 XEncdec_Get_p_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_P;
}

u32 XEncdec_Write_p_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_p_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_p_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_p_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_P_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_P_BASE + offset + i);
    }
    return length;
}

u32 XEncdec_Get_r2_BaseAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE);
}

u32 XEncdec_Get_r2_HighAddress(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH);
}

u32 XEncdec_Get_r2_TotalBytes(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + 1);
}

u32 XEncdec_Get_r2_BitWidth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_WIDTH_R2;
}

u32 XEncdec_Get_r2_Depth(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCDEC_S_AXI_BUNDLE_DEPTH_R2;
}

u32 XEncdec_Write_r2_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_r2_Words(XEncdec *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncdec_Write_r2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncdec_Read_r2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCDEC_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCDEC_S_AXI_BUNDLE_ADDR_R2_BASE + offset + i);
    }
    return length;
}

void XEncdec_InterruptGlobalEnable(XEncdec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_GIE, 1);
}

void XEncdec_InterruptGlobalDisable(XEncdec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_GIE, 0);
}

void XEncdec_InterruptEnable(XEncdec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_IER);
    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_IER, Register | Mask);
}

void XEncdec_InterruptDisable(XEncdec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_IER);
    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_IER, Register & (~Mask));
}

void XEncdec_InterruptClear(XEncdec *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncdec_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_ISR, Mask);
}

u32 XEncdec_InterruptGetEnabled(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_IER);
}

u32 XEncdec_InterruptGetStatus(XEncdec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEncdec_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCDEC_S_AXI_BUNDLE_ADDR_ISR);
}

