// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XENCDEC_H
#define XENCDEC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xencdec_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 S_axi_bundle_BaseAddress;
} XEncdec_Config;
#endif

typedef struct {
    u32 S_axi_bundle_BaseAddress;
    u32 IsReady;
} XEncdec;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XEncdec_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XEncdec_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XEncdec_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XEncdec_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XEncdec_Initialize(XEncdec *InstancePtr, u16 DeviceId);
XEncdec_Config* XEncdec_LookupConfig(u16 DeviceId);
int XEncdec_CfgInitialize(XEncdec *InstancePtr, XEncdec_Config *ConfigPtr);
#else
int XEncdec_Initialize(XEncdec *InstancePtr, const char* InstanceName);
int XEncdec_Release(XEncdec *InstancePtr);
#endif

void XEncdec_Start(XEncdec *InstancePtr);
u32 XEncdec_IsDone(XEncdec *InstancePtr);
u32 XEncdec_IsIdle(XEncdec *InstancePtr);
u32 XEncdec_IsReady(XEncdec *InstancePtr);
void XEncdec_EnableAutoRestart(XEncdec *InstancePtr);
void XEncdec_DisableAutoRestart(XEncdec *InstancePtr);

void XEncdec_Set_arr(XEncdec *InstancePtr, u32 Data);
u32 XEncdec_Get_arr(XEncdec *InstancePtr);
u32 XEncdec_Get_a_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_a_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_a_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_a_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_a_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_a_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_a_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_a_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_a_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Get_c1_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_c1_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_c1_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_c1_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_c1_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_c1_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_c1_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_c1_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_c1_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Get_c2_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_c2_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_c2_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_c2_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_c2_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_c2_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_c2_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_c2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_c2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Get_m_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_m_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_m_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_m_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_m_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_m_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_m_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_m_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_m_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Get_p_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_p_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_p_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_p_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_p_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_p_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_p_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_p_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_p_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Get_r2_BaseAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_r2_HighAddress(XEncdec *InstancePtr);
u32 XEncdec_Get_r2_TotalBytes(XEncdec *InstancePtr);
u32 XEncdec_Get_r2_BitWidth(XEncdec *InstancePtr);
u32 XEncdec_Get_r2_Depth(XEncdec *InstancePtr);
u32 XEncdec_Write_r2_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Read_r2_Words(XEncdec *InstancePtr, int offset, int *data, int length);
u32 XEncdec_Write_r2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);
u32 XEncdec_Read_r2_Bytes(XEncdec *InstancePtr, int offset, char *data, int length);

void XEncdec_InterruptGlobalEnable(XEncdec *InstancePtr);
void XEncdec_InterruptGlobalDisable(XEncdec *InstancePtr);
void XEncdec_InterruptEnable(XEncdec *InstancePtr, u32 Mask);
void XEncdec_InterruptDisable(XEncdec *InstancePtr, u32 Mask);
void XEncdec_InterruptClear(XEncdec *InstancePtr, u32 Mask);
u32 XEncdec_InterruptGetEnabled(XEncdec *InstancePtr);
u32 XEncdec_InterruptGetStatus(XEncdec *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
