// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module knuth_yao2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_we0,
        a_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
output   a_we0;
output  [15:0] a_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] a_address0;
reg a_ce0;
reg a_we0;
reg[15:0] a_d0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] lfsr32;
reg   [31:0] lfsr31;
wire   [31:0] rnd_19_fu_386_p2;
wire   [7:0] i_2_fu_398_p2;
reg   [7:0] i_2_reg_443;
wire    ap_CS_fsm_state2;
reg   [31:0] rnd_2_reg_448;
wire    ap_CS_fsm_state3;
wire    grp_knuth_yao_single_num_fu_184_ap_done;
wire   [7:0] tmp_94_fu_409_p2;
reg   [7:0] tmp_94_reg_453;
wire    ap_CS_fsm_state5;
wire    grp_knuth_yao_single_num_fu_184_ap_start;
wire    grp_knuth_yao_single_num_fu_184_ap_idle;
wire    grp_knuth_yao_single_num_fu_184_ap_ready;
reg   [31:0] grp_knuth_yao_single_num_fu_184_rnd_read;
wire   [31:0] grp_knuth_yao_single_num_fu_184_lfsr32_o;
wire    grp_knuth_yao_single_num_fu_184_lfsr32_o_ap_vld;
wire   [31:0] grp_knuth_yao_single_num_fu_184_lfsr31_o;
wire    grp_knuth_yao_single_num_fu_184_lfsr31_o_ap_vld;
wire   [31:0] grp_knuth_yao_single_num_fu_184_ap_return_0;
wire   [31:0] grp_knuth_yao_single_num_fu_184_ap_return_1;
wire    call_ret_i_i_shift_lfsr_fu_308_ap_ready;
wire   [31:0] call_ret_i_i_shift_lfsr_fu_308_ap_return_0;
wire   [31:0] call_ret_i_i_shift_lfsr_fu_308_ap_return_1;
wire    call_ret6_i_i_shift_lfsr_fu_315_ap_ready;
wire   [31:0] call_ret6_i_i_shift_lfsr_fu_315_ap_return_0;
wire   [31:0] call_ret6_i_i_shift_lfsr_fu_315_ap_return_1;
wire    call_ret5_i_i_shift_lfsr_fu_322_ap_ready;
wire   [31:0] call_ret5_i_i_shift_lfsr_fu_322_ap_return_0;
wire   [31:0] call_ret5_i_i_shift_lfsr_fu_322_ap_return_1;
reg   [31:0] rnd1_reg_162;
reg   [7:0] i_reg_172;
reg    ap_reg_grp_knuth_yao_single_num_fu_184_ap_start;
wire   [0:0] exitcond_fu_392_p2;
wire    ap_CS_fsm_state4;
wire   [63:0] tmp_s_fu_415_p1;
wire   [63:0] tmp_44_fu_430_p1;
wire   [15:0] tmp_fu_404_p1;
wire   [15:0] tmp_95_fu_420_p1;
wire   [31:0] rnd_fu_380_p2;
wire   [7:0] tmp_43_fu_425_p2;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 lfsr32 = 32'd703710;
#0 lfsr31 = 32'd591751049;
#0 ap_reg_grp_knuth_yao_single_num_fu_184_ap_start = 1'b0;
end

knuth_yao_single_num grp_knuth_yao_single_num_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knuth_yao_single_num_fu_184_ap_start),
    .ap_done(grp_knuth_yao_single_num_fu_184_ap_done),
    .ap_idle(grp_knuth_yao_single_num_fu_184_ap_idle),
    .ap_ready(grp_knuth_yao_single_num_fu_184_ap_ready),
    .rnd_read(grp_knuth_yao_single_num_fu_184_rnd_read),
    .lfsr32_i(lfsr32),
    .lfsr32_o(grp_knuth_yao_single_num_fu_184_lfsr32_o),
    .lfsr32_o_ap_vld(grp_knuth_yao_single_num_fu_184_lfsr32_o_ap_vld),
    .lfsr31_i(lfsr31),
    .lfsr31_o(grp_knuth_yao_single_num_fu_184_lfsr31_o),
    .lfsr31_o_ap_vld(grp_knuth_yao_single_num_fu_184_lfsr31_o_ap_vld),
    .ap_return_0(grp_knuth_yao_single_num_fu_184_ap_return_0),
    .ap_return_1(grp_knuth_yao_single_num_fu_184_ap_return_1)
);

shift_lfsr call_ret_i_i_shift_lfsr_fu_308(
    .ap_ready(call_ret_i_i_shift_lfsr_fu_308_ap_ready),
    .lfsr_read(lfsr32),
    .polymonial_mask(32'd3032273756),
    .ap_return_0(call_ret_i_i_shift_lfsr_fu_308_ap_return_0),
    .ap_return_1(call_ret_i_i_shift_lfsr_fu_308_ap_return_1)
);

shift_lfsr call_ret6_i_i_shift_lfsr_fu_315(
    .ap_ready(call_ret6_i_i_shift_lfsr_fu_315_ap_ready),
    .lfsr_read(call_ret_i_i_shift_lfsr_fu_308_ap_return_1),
    .polymonial_mask(32'd3032273756),
    .ap_return_0(call_ret6_i_i_shift_lfsr_fu_315_ap_return_0),
    .ap_return_1(call_ret6_i_i_shift_lfsr_fu_315_ap_return_1)
);

shift_lfsr call_ret5_i_i_shift_lfsr_fu_322(
    .ap_ready(call_ret5_i_i_shift_lfsr_fu_322_ap_ready),
    .lfsr_read(lfsr31),
    .polymonial_mask(32'd2052834019),
    .ap_return_0(call_ret5_i_i_shift_lfsr_fu_322_ap_return_0),
    .ap_return_1(call_ret5_i_i_shift_lfsr_fu_322_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_knuth_yao_single_num_fu_184_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_392_p2 == 1'd0)))) begin
            ap_reg_grp_knuth_yao_single_num_fu_184_ap_start <= 1'b1;
        end else if ((grp_knuth_yao_single_num_fu_184_ap_ready == 1'b1)) begin
            ap_reg_grp_knuth_yao_single_num_fu_184_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_reg_172 <= i_2_reg_443;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_172 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lfsr31 <= call_ret5_i_i_shift_lfsr_fu_322_ap_return_1;
    end else if ((((grp_knuth_yao_single_num_fu_184_lfsr31_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_knuth_yao_single_num_fu_184_lfsr31_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        lfsr31 <= grp_knuth_yao_single_num_fu_184_lfsr31_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lfsr32 <= call_ret6_i_i_shift_lfsr_fu_315_ap_return_1;
    end else if ((((grp_knuth_yao_single_num_fu_184_lfsr32_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_knuth_yao_single_num_fu_184_lfsr32_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        lfsr32 <= grp_knuth_yao_single_num_fu_184_lfsr32_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rnd1_reg_162 <= grp_knuth_yao_single_num_fu_184_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        rnd1_reg_162 <= rnd_19_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_443 <= i_2_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rnd_2_reg_448 <= grp_knuth_yao_single_num_fu_184_ap_return_1;
        tmp_94_reg_453[7 : 1] <= tmp_94_fu_409_p2[7 : 1];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        a_address0 = tmp_44_fu_430_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        a_address0 = tmp_s_fu_415_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        a_d0 = tmp_95_fu_420_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        a_d0 = tmp_fu_404_p1;
    end else begin
        a_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        a_we0 = 1'b1;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_392_p2 == 1'd1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_392_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_knuth_yao_single_num_fu_184_rnd_read = rnd_2_reg_448;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_knuth_yao_single_num_fu_184_rnd_read = rnd1_reg_162;
    end else begin
        grp_knuth_yao_single_num_fu_184_rnd_read = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_392_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_knuth_yao_single_num_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign exitcond_fu_392_p2 = ((i_reg_172 == 8'd128) ? 1'b1 : 1'b0);

assign grp_knuth_yao_single_num_fu_184_ap_start = ap_reg_grp_knuth_yao_single_num_fu_184_ap_start;

assign i_2_fu_398_p2 = (i_reg_172 + 8'd1);

assign rnd_19_fu_386_p2 = (rnd_fu_380_p2 | 32'd2147483648);

assign rnd_fu_380_p2 = (call_ret6_i_i_shift_lfsr_fu_315_ap_return_0 ^ call_ret5_i_i_shift_lfsr_fu_322_ap_return_0);

assign tmp_43_fu_425_p2 = (tmp_94_reg_453 | 8'd1);

assign tmp_44_fu_430_p1 = tmp_43_fu_425_p2;

assign tmp_94_fu_409_p2 = i_reg_172 << 8'd1;

assign tmp_95_fu_420_p1 = grp_knuth_yao_single_num_fu_184_ap_return_0[15:0];

assign tmp_fu_404_p1 = grp_knuth_yao_single_num_fu_184_ap_return_0[15:0];

assign tmp_s_fu_415_p1 = tmp_94_fu_409_p2;

always @ (posedge ap_clk) begin
    tmp_94_reg_453[0] <= 1'b0;
end

endmodule //knuth_yao2
