// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mod_r (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [14:0] ap_return;
input   ap_ce;

reg[14:0] ap_return;

reg   [31:0] x_read_reg_170;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] lowbits_r_fu_56_p1;
reg   [31:0] lowbits_r_reg_175;
reg   [31:0] lowbits_l_reg_180;
wire   [13:0] ret3_fu_137_p2;
reg   [13:0] ret3_reg_185;
reg   [0:0] tmp_6_reg_191;
wire    ap_block_pp0_stage0;
wire  signed [31:0] lowbits_fu_50_p1;
wire   [63:0] lowbits_fu_50_p2;
wire   [31:0] pp1_fu_73_p1;
wire   [31:0] pp2_fu_82_p1;
wire   [44:0] pp1_fu_73_p2;
wire   [12:0] tmp_7_fu_88_p4;
wire   [44:0] pp1_1_cast_fu_98_p1;
wire   [44:0] pp2_fu_82_p2;
wire   [44:0] pp2_1_fu_102_p2;
wire   [12:0] tmp_8_fu_108_p4;
wire   [0:0] tmp_5_fu_122_p3;
wire   [13:0] ret3_cast_fu_118_p1;
wire   [13:0] tmp_29_cast_cast_fu_129_p3;
wire   [13:0] tmp_s_fu_154_p2;
wire   [14:0] tmp_33_cast_fu_159_p1;
wire  signed [14:0] tmp_32_cast_fu_151_p1;
wire   [14:0] tmp_2_fu_163_p3;
reg    ap_ce_reg;
reg   [31:0] x_int_reg;
reg   [14:0] ap_return_int_reg;
wire   [44:0] pp1_fu_73_p10;
wire   [44:0] pp2_fu_82_p10;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= tmp_2_fu_163_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        lowbits_l_reg_180 <= {{lowbits_fu_50_p2[63:32]}};
        lowbits_r_reg_175 <= lowbits_r_fu_56_p1;
        ret3_reg_185 <= ret3_fu_137_p2;
        tmp_6_reg_191 <= ret3_fu_137_p2[32'd13];
        x_read_reg_170 <= x_int_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = tmp_2_fu_163_p3;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign lowbits_fu_50_p1 = x_int_reg;

assign lowbits_fu_50_p2 = ($signed({{1'b0}, {64'd2401607092007494}}) * $signed(lowbits_fu_50_p1));

assign lowbits_r_fu_56_p1 = lowbits_fu_50_p2[31:0];

assign pp1_1_cast_fu_98_p1 = tmp_7_fu_88_p4;

assign pp1_fu_73_p1 = pp1_fu_73_p10;

assign pp1_fu_73_p10 = lowbits_r_reg_175;

assign pp1_fu_73_p2 = (45'd7681 * pp1_fu_73_p1);

assign pp2_1_fu_102_p2 = (pp1_1_cast_fu_98_p1 + pp2_fu_82_p2);

assign pp2_fu_82_p1 = pp2_fu_82_p10;

assign pp2_fu_82_p10 = lowbits_l_reg_180;

assign pp2_fu_82_p2 = (45'd7681 * pp2_fu_82_p1);

assign ret3_cast_fu_118_p1 = tmp_8_fu_108_p4;

assign ret3_fu_137_p2 = (ret3_cast_fu_118_p1 - tmp_29_cast_cast_fu_129_p3);

assign tmp_29_cast_cast_fu_129_p3 = ((tmp_5_fu_122_p3[0:0] === 1'b1) ? 14'd7680 : 14'd0);

assign tmp_2_fu_163_p3 = ((tmp_6_reg_191[0:0] === 1'b1) ? tmp_33_cast_fu_159_p1 : tmp_32_cast_fu_151_p1);

assign tmp_32_cast_fu_151_p1 = $signed(ret3_reg_185);

assign tmp_33_cast_fu_159_p1 = tmp_s_fu_154_p2;

assign tmp_5_fu_122_p3 = x_read_reg_170[32'd31];

assign tmp_7_fu_88_p4 = {{pp1_fu_73_p2[44:32]}};

assign tmp_8_fu_108_p4 = {{pp2_1_fu_102_p2[44:32]}};

assign tmp_s_fu_154_p2 = (14'd7681 + ret3_reg_185);

endmodule //mod_r
