// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RLWE_enc2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        c1_address0,
        c1_ce0,
        c1_we0,
        c1_d0,
        c1_q0,
        c2_address0,
        c2_ce0,
        c2_we0,
        c2_d0,
        c2_q0,
        m_address0,
        m_ce0,
        m_q0,
        p_address0,
        p_ce0,
        p_q0
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_pp0_stage0 = 22'd2;
parameter    ap_ST_fsm_state4 = 22'd4;
parameter    ap_ST_fsm_state5 = 22'd8;
parameter    ap_ST_fsm_state6 = 22'd16;
parameter    ap_ST_fsm_state7 = 22'd32;
parameter    ap_ST_fsm_state8 = 22'd64;
parameter    ap_ST_fsm_state9 = 22'd128;
parameter    ap_ST_fsm_pp1_stage0 = 22'd256;
parameter    ap_ST_fsm_state16 = 22'd512;
parameter    ap_ST_fsm_state17 = 22'd1024;
parameter    ap_ST_fsm_pp2_stage0 = 22'd2048;
parameter    ap_ST_fsm_state24 = 22'd4096;
parameter    ap_ST_fsm_pp3_stage0 = 22'd8192;
parameter    ap_ST_fsm_pp3_stage1 = 22'd16384;
parameter    ap_ST_fsm_state31 = 22'd32768;
parameter    ap_ST_fsm_pp4_stage0 = 22'd65536;
parameter    ap_ST_fsm_state38 = 22'd131072;
parameter    ap_ST_fsm_pp5_stage0 = 22'd262144;
parameter    ap_ST_fsm_pp5_stage1 = 22'd524288;
parameter    ap_ST_fsm_state45 = 22'd1048576;
parameter    ap_ST_fsm_state46 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
input  [15:0] a_q0;
output  [7:0] c1_address0;
output   c1_ce0;
output   c1_we0;
output  [15:0] c1_d0;
input  [15:0] c1_q0;
output  [7:0] c2_address0;
output   c2_ce0;
output   c2_we0;
output  [15:0] c2_d0;
input  [15:0] c2_q0;
output  [7:0] m_address0;
output   m_ce0;
input  [15:0] m_q0;
output  [7:0] p_address0;
output   p_ce0;
input  [15:0] p_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_ce0;
reg[7:0] c1_address0;
reg c1_ce0;
reg c1_we0;
reg[15:0] c1_d0;
reg[7:0] c2_address0;
reg c2_ce0;
reg c2_we0;
reg[15:0] c2_d0;
reg m_ce0;
reg p_ce0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] i_reg_340;
reg   [8:0] j_i_reg_351;
reg   [8:0] j_i7_reg_362;
reg   [8:0] j_i1_reg_373;
reg   [8:0] j_i2_reg_384;
reg   [8:0] j_i3_reg_395;
wire   [0:0] exitcond_fu_567_p2;
reg   [0:0] exitcond_reg_800;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] i_5_fu_573_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] tmp_fu_579_p1;
reg   [63:0] tmp_reg_809;
wire   [0:0] exitcond_i_fu_603_p2;
reg   [0:0] exitcond_i_reg_819;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state10_pp1_stage0_iter0;
wire    ap_block_state11_pp1_stage0_iter1;
wire    ap_block_state12_pp1_stage0_iter2;
wire    ap_block_state13_pp1_stage0_iter3;
wire    ap_block_state14_pp1_stage0_iter4;
wire    ap_block_state15_pp1_stage0_iter5;
wire    ap_block_pp1_stage0_11001;
reg   [0:0] ap_reg_pp1_iter1_exitcond_i_reg_819;
reg   [0:0] ap_reg_pp1_iter2_exitcond_i_reg_819;
reg   [0:0] ap_reg_pp1_iter3_exitcond_i_reg_819;
reg   [0:0] ap_reg_pp1_iter4_exitcond_i_reg_819;
wire   [8:0] j_fu_609_p2;
reg    ap_enable_reg_pp1_iter0;
reg   [7:0] e3_addr_reg_828;
reg   [7:0] ap_reg_pp1_iter1_e3_addr_reg_828;
reg   [7:0] ap_reg_pp1_iter2_e3_addr_reg_828;
reg   [7:0] ap_reg_pp1_iter3_e3_addr_reg_828;
reg   [7:0] ap_reg_pp1_iter4_e3_addr_reg_828;
wire   [16:0] tmp_176_i_fu_629_p2;
reg   [16:0] tmp_176_i_reg_839;
wire   [31:0] tmp_176_i_cast_fu_635_p1;
wire   [0:0] exitcond_i8_fu_644_p2;
reg   [0:0] exitcond_i8_reg_849;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state18_pp2_stage0_iter0;
wire    ap_block_state19_pp2_stage0_iter1;
wire    ap_block_state20_pp2_stage0_iter2;
wire    ap_block_state21_pp2_stage0_iter3;
wire    ap_block_state22_pp2_stage0_iter4;
wire    ap_block_state23_pp2_stage0_iter5;
wire    ap_block_pp2_stage0_11001;
reg   [0:0] ap_reg_pp2_iter1_exitcond_i8_reg_849;
reg   [0:0] ap_reg_pp2_iter2_exitcond_i8_reg_849;
reg   [0:0] ap_reg_pp2_iter3_exitcond_i8_reg_849;
reg   [0:0] ap_reg_pp2_iter4_exitcond_i8_reg_849;
wire   [8:0] j_10_fu_650_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [63:0] tmp_i9_fu_656_p1;
reg   [63:0] tmp_i9_reg_858;
reg   [63:0] ap_reg_pp2_iter1_tmp_i9_reg_858;
reg   [63:0] ap_reg_pp2_iter2_tmp_i9_reg_858;
reg   [63:0] ap_reg_pp2_iter3_tmp_i9_reg_858;
reg   [63:0] ap_reg_pp2_iter4_tmp_i9_reg_858;
wire   [31:0] tmp_173_i_fu_788_p2;
reg   [31:0] tmp_173_i_reg_873;
wire   [0:0] exitcond_i1_fu_675_p2;
reg   [0:0] exitcond_i1_reg_878;
wire    ap_CS_fsm_pp3_stage0;
wire    ap_block_state25_pp3_stage0_iter0;
wire    ap_block_state27_pp3_stage0_iter1;
wire    ap_block_state29_pp3_stage0_iter2;
wire    ap_block_pp3_stage0_11001;
reg   [0:0] ap_reg_pp3_iter1_exitcond_i1_reg_878;
reg   [0:0] ap_reg_pp3_iter2_exitcond_i1_reg_878;
wire   [8:0] j_11_fu_681_p2;
reg   [8:0] j_11_reg_882;
reg    ap_enable_reg_pp3_iter0;
reg   [7:0] c1_addr_3_reg_892;
reg   [7:0] ap_reg_pp3_iter1_c1_addr_3_reg_892;
reg   [7:0] ap_reg_pp3_iter2_c1_addr_3_reg_892;
wire   [16:0] tmp_177_i1_fu_701_p2;
reg   [16:0] tmp_177_i1_reg_897;
wire    ap_CS_fsm_pp3_stage1;
wire    ap_block_state26_pp3_stage1_iter0;
wire    ap_block_state28_pp3_stage1_iter1;
wire    ap_block_state30_pp3_stage1_iter2;
wire    ap_block_pp3_stage1_11001;
wire   [31:0] tmp_177_i1_cast_fu_707_p1;
wire   [0:0] exitcond_i2_fu_716_p2;
reg   [0:0] exitcond_i2_reg_907;
wire    ap_CS_fsm_pp4_stage0;
wire    ap_block_state32_pp4_stage0_iter0;
wire    ap_block_state33_pp4_stage0_iter1;
wire    ap_block_state34_pp4_stage0_iter2;
wire    ap_block_state35_pp4_stage0_iter3;
wire    ap_block_state36_pp4_stage0_iter4;
wire    ap_block_state37_pp4_stage0_iter5;
wire    ap_block_pp4_stage0_11001;
reg   [0:0] ap_reg_pp4_iter1_exitcond_i2_reg_907;
reg   [0:0] ap_reg_pp4_iter2_exitcond_i2_reg_907;
reg   [0:0] ap_reg_pp4_iter3_exitcond_i2_reg_907;
reg   [0:0] ap_reg_pp4_iter4_exitcond_i2_reg_907;
wire   [8:0] j_12_fu_722_p2;
reg    ap_enable_reg_pp4_iter0;
wire   [63:0] tmp_i2_fu_728_p1;
reg   [63:0] tmp_i2_reg_916;
reg   [63:0] ap_reg_pp4_iter1_tmp_i2_reg_916;
reg   [63:0] ap_reg_pp4_iter2_tmp_i2_reg_916;
reg   [63:0] ap_reg_pp4_iter3_tmp_i2_reg_916;
reg   [63:0] ap_reg_pp4_iter4_tmp_i2_reg_916;
wire   [31:0] tmp_173_i1_fu_794_p2;
reg   [31:0] tmp_173_i1_reg_931;
wire   [0:0] exitcond_i3_fu_747_p2;
reg   [0:0] exitcond_i3_reg_936;
wire    ap_CS_fsm_pp5_stage0;
wire    ap_block_state39_pp5_stage0_iter0;
wire    ap_block_state41_pp5_stage0_iter1;
wire    ap_block_state43_pp5_stage0_iter2;
wire    ap_block_pp5_stage0_11001;
reg   [0:0] ap_reg_pp5_iter1_exitcond_i3_reg_936;
reg   [0:0] ap_reg_pp5_iter2_exitcond_i3_reg_936;
wire   [8:0] j_13_fu_753_p2;
reg   [8:0] j_13_reg_940;
reg    ap_enable_reg_pp5_iter0;
reg   [7:0] c2_addr_1_reg_950;
reg   [7:0] ap_reg_pp5_iter1_c2_addr_1_reg_950;
reg   [7:0] ap_reg_pp5_iter2_c2_addr_1_reg_950;
wire   [16:0] tmp_177_i2_fu_773_p2;
reg   [16:0] tmp_177_i2_reg_955;
wire    ap_CS_fsm_pp5_stage1;
wire    ap_block_state40_pp5_stage1_iter0;
wire    ap_block_state42_pp5_stage1_iter1;
wire    ap_block_state44_pp5_stage1_iter2;
wire    ap_block_pp5_stage1_11001;
wire   [31:0] tmp_177_i2_cast_fu_779_p1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_CS_fsm_state9;
wire    grp_knuth_yao2_fu_406_ap_done;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state10;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
wire    ap_CS_fsm_state17;
wire    grp_fwd_ntt2_fu_529_ap_done;
wire    grp_fwd_ntt2_fu_536_ap_done;
wire    grp_fwd_ntt2_fu_543_ap_done;
reg    ap_block_state17_on_subcall_done;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state18;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
wire    ap_CS_fsm_state24;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state25;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage1_subdone;
reg    ap_enable_reg_pp3_iter2;
wire    ap_CS_fsm_state31;
wire    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state32;
reg    ap_enable_reg_pp4_iter1;
reg    ap_enable_reg_pp4_iter2;
reg    ap_enable_reg_pp4_iter3;
reg    ap_enable_reg_pp4_iter4;
reg    ap_enable_reg_pp4_iter5;
wire    ap_CS_fsm_state38;
wire    ap_block_pp5_stage0_subdone;
reg    ap_condition_pp5_exit_iter0_state39;
reg    ap_enable_reg_pp5_iter1;
wire    ap_block_pp5_stage1_subdone;
reg    ap_enable_reg_pp5_iter2;
reg   [7:0] e1_address0;
reg    e1_ce0;
reg    e1_we0;
reg   [15:0] e1_d0;
wire   [15:0] e1_q0;
reg    e1_ce1;
reg    e1_we1;
wire   [15:0] e1_q1;
reg   [7:0] e2_address0;
reg    e2_ce0;
reg    e2_we0;
reg   [15:0] e2_d0;
wire   [15:0] e2_q0;
reg    e2_ce1;
reg    e2_we1;
wire   [15:0] e2_q1;
reg   [7:0] e3_address0;
reg    e3_ce0;
reg    e3_we0;
reg   [15:0] e3_d0;
wire   [15:0] e3_q0;
reg   [7:0] e3_address1;
reg    e3_ce1;
reg    e3_we1;
reg   [15:0] e3_d1;
wire   [15:0] e3_q1;
reg   [7:0] encoded_m_address0;
reg    encoded_m_ce0;
reg    encoded_m_we0;
wire   [15:0] encoded_m_d0;
wire   [15:0] encoded_m_q0;
wire    grp_knuth_yao2_fu_406_ap_start;
wire    grp_knuth_yao2_fu_406_ap_idle;
wire    grp_knuth_yao2_fu_406_ap_ready;
wire   [7:0] grp_knuth_yao2_fu_406_a_address0;
wire    grp_knuth_yao2_fu_406_a_ce0;
wire    grp_knuth_yao2_fu_406_a_we0;
wire   [15:0] grp_knuth_yao2_fu_406_a_d0;
wire    grp_fwd_ntt2_fu_529_ap_start;
wire    grp_fwd_ntt2_fu_529_ap_idle;
wire    grp_fwd_ntt2_fu_529_ap_ready;
wire   [7:0] grp_fwd_ntt2_fu_529_a_address0;
wire    grp_fwd_ntt2_fu_529_a_ce0;
wire    grp_fwd_ntt2_fu_529_a_we0;
wire   [15:0] grp_fwd_ntt2_fu_529_a_d0;
wire   [7:0] grp_fwd_ntt2_fu_529_a_address1;
wire    grp_fwd_ntt2_fu_529_a_ce1;
wire    grp_fwd_ntt2_fu_529_a_we1;
wire   [15:0] grp_fwd_ntt2_fu_529_a_d1;
wire    grp_fwd_ntt2_fu_536_ap_start;
wire    grp_fwd_ntt2_fu_536_ap_idle;
wire    grp_fwd_ntt2_fu_536_ap_ready;
wire   [7:0] grp_fwd_ntt2_fu_536_a_address0;
wire    grp_fwd_ntt2_fu_536_a_ce0;
wire    grp_fwd_ntt2_fu_536_a_we0;
wire   [15:0] grp_fwd_ntt2_fu_536_a_d0;
wire   [7:0] grp_fwd_ntt2_fu_536_a_address1;
wire    grp_fwd_ntt2_fu_536_a_ce1;
wire    grp_fwd_ntt2_fu_536_a_we1;
wire   [15:0] grp_fwd_ntt2_fu_536_a_d1;
wire    grp_fwd_ntt2_fu_543_ap_start;
wire    grp_fwd_ntt2_fu_543_ap_idle;
wire    grp_fwd_ntt2_fu_543_ap_ready;
wire   [7:0] grp_fwd_ntt2_fu_543_a_address0;
wire    grp_fwd_ntt2_fu_543_a_ce0;
wire    grp_fwd_ntt2_fu_543_a_we0;
wire   [15:0] grp_fwd_ntt2_fu_543_a_d0;
wire   [7:0] grp_fwd_ntt2_fu_543_a_address1;
wire    grp_fwd_ntt2_fu_543_a_ce1;
wire    grp_fwd_ntt2_fu_543_a_we1;
wire   [15:0] grp_fwd_ntt2_fu_543_a_d1;
reg   [31:0] grp_mod_r_fu_550_x;
wire   [14:0] grp_mod_r_fu_550_ap_return;
reg    grp_mod_r_fu_550_ap_ce;
wire    grp_rearrange2_fu_555_ap_start;
wire    grp_rearrange2_fu_555_ap_done;
wire    grp_rearrange2_fu_555_ap_idle;
wire    grp_rearrange2_fu_555_ap_ready;
wire   [7:0] grp_rearrange2_fu_555_a_address0;
wire    grp_rearrange2_fu_555_a_ce0;
wire    grp_rearrange2_fu_555_a_we0;
wire   [15:0] grp_rearrange2_fu_555_a_d0;
wire    grp_rearrange2_fu_561_ap_start;
wire    grp_rearrange2_fu_561_ap_done;
wire    grp_rearrange2_fu_561_ap_idle;
wire    grp_rearrange2_fu_561_ap_ready;
wire   [7:0] grp_rearrange2_fu_561_a_address0;
wire    grp_rearrange2_fu_561_a_ce0;
wire    grp_rearrange2_fu_561_a_we0;
wire   [15:0] grp_rearrange2_fu_561_a_d0;
reg   [8:0] ap_phi_mux_j_i1_phi_fu_377_p4;
wire    ap_block_pp3_stage0;
reg   [8:0] ap_phi_mux_j_i3_phi_fu_399_p4;
wire    ap_block_pp5_stage0;
reg    ap_reg_grp_knuth_yao2_fu_406_ap_start;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
reg    ap_reg_grp_fwd_ntt2_fu_529_ap_start;
wire    ap_CS_fsm_state16;
reg    ap_reg_grp_fwd_ntt2_fu_536_ap_start;
reg    ap_reg_grp_fwd_ntt2_fu_543_ap_start;
wire    ap_block_pp1_stage0;
wire    ap_block_pp2_stage0;
wire    ap_block_pp4_stage0;
reg    ap_reg_grp_rearrange2_fu_555_ap_start;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state46;
reg    ap_reg_grp_rearrange2_fu_561_ap_start;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_i_fu_615_p1;
wire   [63:0] tmp_i1_94_fu_687_p1;
wire   [63:0] tmp_i3_99_fu_759_p1;
wire  signed [15:0] p_trunc_ext_fu_639_p1;
wire  signed [15:0] p_trunc7_ext_fu_670_p1;
wire  signed [15:0] p_trunc8_ext_fu_711_p1;
wire    ap_block_pp3_stage1;
wire  signed [15:0] p_trunc9_ext_fu_742_p1;
wire  signed [15:0] p_trunc10_ext_fu_783_p1;
wire    ap_block_pp5_stage1;
wire   [15:0] tmp_158_fu_584_p2;
wire   [15:0] tmp_159_fu_590_p2;
wire   [16:0] tmp_i_cast_fu_621_p1;
wire   [16:0] tmp_175_i_cast_fu_625_p1;
wire   [16:0] tmp_i2_cast_fu_693_p1;
wire   [16:0] tmp_176_i1_cast_fu_697_p1;
wire   [16:0] tmp_i4_cast_fu_765_p1;
wire   [16:0] tmp_176_i2_cast_fu_769_p1;
wire   [15:0] tmp_173_i_fu_788_p0;
wire   [15:0] tmp_173_i_fu_788_p1;
wire   [15:0] tmp_173_i1_fu_794_p0;
wire   [15:0] tmp_173_i1_fu_794_p1;
reg    ap_block_state46_on_subcall_done;
reg   [21:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
reg    ap_idle_pp5;
wire    ap_enable_pp5;
wire   [31:0] tmp_173_i1_fu_794_p00;
wire   [31:0] tmp_173_i1_fu_794_p10;
wire   [31:0] tmp_173_i_fu_788_p00;
wire   [31:0] tmp_173_i_fu_788_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter2 = 1'b0;
#0 ap_enable_reg_pp4_iter3 = 1'b0;
#0 ap_enable_reg_pp4_iter4 = 1'b0;
#0 ap_enable_reg_pp4_iter5 = 1'b0;
#0 ap_enable_reg_pp5_iter1 = 1'b0;
#0 ap_enable_reg_pp5_iter2 = 1'b0;
#0 ap_reg_grp_knuth_yao2_fu_406_ap_start = 1'b0;
#0 ap_reg_grp_fwd_ntt2_fu_529_ap_start = 1'b0;
#0 ap_reg_grp_fwd_ntt2_fu_536_ap_start = 1'b0;
#0 ap_reg_grp_fwd_ntt2_fu_543_ap_start = 1'b0;
#0 ap_reg_grp_rearrange2_fu_555_ap_start = 1'b0;
#0 ap_reg_grp_rearrange2_fu_561_ap_start = 1'b0;
end

RLWE_enc2_e1 #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
e1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e1_address0),
    .ce0(e1_ce0),
    .we0(e1_we0),
    .d0(e1_d0),
    .q0(e1_q0),
    .address1(grp_fwd_ntt2_fu_529_a_address1),
    .ce1(e1_ce1),
    .we1(e1_we1),
    .d1(grp_fwd_ntt2_fu_529_a_d1),
    .q1(e1_q1)
);

RLWE_enc2_e1 #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
e2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e2_address0),
    .ce0(e2_ce0),
    .we0(e2_we0),
    .d0(e2_d0),
    .q0(e2_q0),
    .address1(grp_fwd_ntt2_fu_536_a_address1),
    .ce1(e2_ce1),
    .we1(e2_we1),
    .d1(grp_fwd_ntt2_fu_536_a_d1),
    .q1(e2_q1)
);

RLWE_enc2_e1 #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
e3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e3_address0),
    .ce0(e3_ce0),
    .we0(e3_we0),
    .d0(e3_d0),
    .q0(e3_q0),
    .address1(e3_address1),
    .ce1(e3_ce1),
    .we1(e3_we1),
    .d1(e3_d1),
    .q1(e3_q1)
);

RLWE_enc2_encoded_m #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
encoded_m_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(encoded_m_address0),
    .ce0(encoded_m_ce0),
    .we0(encoded_m_we0),
    .d0(encoded_m_d0),
    .q0(encoded_m_q0)
);

knuth_yao2 grp_knuth_yao2_fu_406(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knuth_yao2_fu_406_ap_start),
    .ap_done(grp_knuth_yao2_fu_406_ap_done),
    .ap_idle(grp_knuth_yao2_fu_406_ap_idle),
    .ap_ready(grp_knuth_yao2_fu_406_ap_ready),
    .a_address0(grp_knuth_yao2_fu_406_a_address0),
    .a_ce0(grp_knuth_yao2_fu_406_a_ce0),
    .a_we0(grp_knuth_yao2_fu_406_a_we0),
    .a_d0(grp_knuth_yao2_fu_406_a_d0)
);

fwd_ntt2 grp_fwd_ntt2_fu_529(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fwd_ntt2_fu_529_ap_start),
    .ap_done(grp_fwd_ntt2_fu_529_ap_done),
    .ap_idle(grp_fwd_ntt2_fu_529_ap_idle),
    .ap_ready(grp_fwd_ntt2_fu_529_ap_ready),
    .a_address0(grp_fwd_ntt2_fu_529_a_address0),
    .a_ce0(grp_fwd_ntt2_fu_529_a_ce0),
    .a_we0(grp_fwd_ntt2_fu_529_a_we0),
    .a_d0(grp_fwd_ntt2_fu_529_a_d0),
    .a_q0(e1_q0),
    .a_address1(grp_fwd_ntt2_fu_529_a_address1),
    .a_ce1(grp_fwd_ntt2_fu_529_a_ce1),
    .a_we1(grp_fwd_ntt2_fu_529_a_we1),
    .a_d1(grp_fwd_ntt2_fu_529_a_d1),
    .a_q1(e1_q1)
);

fwd_ntt2 grp_fwd_ntt2_fu_536(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fwd_ntt2_fu_536_ap_start),
    .ap_done(grp_fwd_ntt2_fu_536_ap_done),
    .ap_idle(grp_fwd_ntt2_fu_536_ap_idle),
    .ap_ready(grp_fwd_ntt2_fu_536_ap_ready),
    .a_address0(grp_fwd_ntt2_fu_536_a_address0),
    .a_ce0(grp_fwd_ntt2_fu_536_a_ce0),
    .a_we0(grp_fwd_ntt2_fu_536_a_we0),
    .a_d0(grp_fwd_ntt2_fu_536_a_d0),
    .a_q0(e2_q0),
    .a_address1(grp_fwd_ntt2_fu_536_a_address1),
    .a_ce1(grp_fwd_ntt2_fu_536_a_ce1),
    .a_we1(grp_fwd_ntt2_fu_536_a_we1),
    .a_d1(grp_fwd_ntt2_fu_536_a_d1),
    .a_q1(e2_q1)
);

fwd_ntt2 grp_fwd_ntt2_fu_543(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fwd_ntt2_fu_543_ap_start),
    .ap_done(grp_fwd_ntt2_fu_543_ap_done),
    .ap_idle(grp_fwd_ntt2_fu_543_ap_idle),
    .ap_ready(grp_fwd_ntt2_fu_543_ap_ready),
    .a_address0(grp_fwd_ntt2_fu_543_a_address0),
    .a_ce0(grp_fwd_ntt2_fu_543_a_ce0),
    .a_we0(grp_fwd_ntt2_fu_543_a_we0),
    .a_d0(grp_fwd_ntt2_fu_543_a_d0),
    .a_q0(e3_q0),
    .a_address1(grp_fwd_ntt2_fu_543_a_address1),
    .a_ce1(grp_fwd_ntt2_fu_543_a_ce1),
    .a_we1(grp_fwd_ntt2_fu_543_a_we1),
    .a_d1(grp_fwd_ntt2_fu_543_a_d1),
    .a_q1(e3_q1)
);

mod_r grp_mod_r_fu_550(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(grp_mod_r_fu_550_x),
    .ap_return(grp_mod_r_fu_550_ap_return),
    .ap_ce(grp_mod_r_fu_550_ap_ce)
);

rearrange2 grp_rearrange2_fu_555(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rearrange2_fu_555_ap_start),
    .ap_done(grp_rearrange2_fu_555_ap_done),
    .ap_idle(grp_rearrange2_fu_555_ap_idle),
    .ap_ready(grp_rearrange2_fu_555_ap_ready),
    .a_address0(grp_rearrange2_fu_555_a_address0),
    .a_ce0(grp_rearrange2_fu_555_a_ce0),
    .a_we0(grp_rearrange2_fu_555_a_we0),
    .a_d0(grp_rearrange2_fu_555_a_d0),
    .a_q0(c1_q0)
);

rearrange2 grp_rearrange2_fu_561(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rearrange2_fu_561_ap_start),
    .ap_done(grp_rearrange2_fu_561_ap_done),
    .ap_idle(grp_rearrange2_fu_561_ap_idle),
    .ap_ready(grp_rearrange2_fu_561_ap_ready),
    .a_address0(grp_rearrange2_fu_561_a_address0),
    .a_ce0(grp_rearrange2_fu_561_a_ce0),
    .a_we0(grp_rearrange2_fu_561_a_we0),
    .a_d0(grp_rearrange2_fu_561_a_d0),
    .a_q0(c2_q0)
);

encdec_mul_mul_167jG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_167jG_U77(
    .din0(tmp_173_i_fu_788_p0),
    .din1(tmp_173_i_fu_788_p1),
    .dout(tmp_173_i_fu_788_p2)
);

encdec_mul_mul_167jG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_167jG_U78(
    .din0(tmp_173_i1_fu_794_p0),
    .din1(tmp_173_i1_fu_794_p1),
    .dout(tmp_173_i1_fu_794_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state10) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state10)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state10);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end else if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state18) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state18)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state18);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
            ap_enable_reg_pp2_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state25) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage1_subdone) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state25)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state25);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage1_subdone) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state32) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state31)) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp4_exit_iter0_state32)) begin
                ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state32);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter2 <= ap_enable_reg_pp4_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter3 <= ap_enable_reg_pp4_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter4 <= ap_enable_reg_pp4_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter5 <= ap_enable_reg_pp4_iter4;
        end else if ((1'b1 == ap_CS_fsm_state31)) begin
            ap_enable_reg_pp4_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp5_stage0_subdone) & (1'b1 == ap_condition_pp5_exit_iter0_state39) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
            ap_enable_reg_pp5_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state38)) begin
            ap_enable_reg_pp5_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp5_stage1_subdone) & (1'b1 == ap_CS_fsm_pp5_stage1))) begin
            if ((1'b1 == ap_condition_pp5_exit_iter0_state39)) begin
                ap_enable_reg_pp5_iter1 <= (1'b1 ^ ap_condition_pp5_exit_iter0_state39);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp5_iter1 <= ap_enable_reg_pp5_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp5_stage1_subdone) & (1'b1 == ap_CS_fsm_pp5_stage1))) begin
            ap_enable_reg_pp5_iter2 <= ap_enable_reg_pp5_iter1;
        end else if ((1'b1 == ap_CS_fsm_state38)) begin
            ap_enable_reg_pp5_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_fwd_ntt2_fu_529_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_reg_grp_fwd_ntt2_fu_529_ap_start <= 1'b1;
        end else if ((grp_fwd_ntt2_fu_529_ap_ready == 1'b1)) begin
            ap_reg_grp_fwd_ntt2_fu_529_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_fwd_ntt2_fu_536_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_reg_grp_fwd_ntt2_fu_536_ap_start <= 1'b1;
        end else if ((grp_fwd_ntt2_fu_536_ap_ready == 1'b1)) begin
            ap_reg_grp_fwd_ntt2_fu_536_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_fwd_ntt2_fu_543_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_reg_grp_fwd_ntt2_fu_543_ap_start <= 1'b1;
        end else if ((grp_fwd_ntt2_fu_543_ap_ready == 1'b1)) begin
            ap_reg_grp_fwd_ntt2_fu_543_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_knuth_yao2_fu_406_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
            ap_reg_grp_knuth_yao2_fu_406_ap_start <= 1'b1;
        end else if ((grp_knuth_yao2_fu_406_ap_ready == 1'b1)) begin
            ap_reg_grp_knuth_yao2_fu_406_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_rearrange2_fu_555_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state45)) begin
            ap_reg_grp_rearrange2_fu_555_ap_start <= 1'b1;
        end else if ((grp_rearrange2_fu_555_ap_ready == 1'b1)) begin
            ap_reg_grp_rearrange2_fu_555_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_rearrange2_fu_561_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state45)) begin
            ap_reg_grp_rearrange2_fu_561_ap_start <= 1'b1;
        end else if ((grp_rearrange2_fu_561_ap_ready == 1'b1)) begin
            ap_reg_grp_rearrange2_fu_561_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_567_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_340 <= i_5_fu_573_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_340 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        j_i1_reg_373 <= 9'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (exitcond_i1_reg_878 == 1'd0))) begin
        j_i1_reg_373 <= j_11_reg_882;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        j_i2_reg_384 <= 9'd0;
    end else if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (exitcond_i2_fu_716_p2 == 1'd0))) begin
        j_i2_reg_384 <= j_12_fu_722_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        j_i3_reg_395 <= 9'd0;
    end else if (((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (exitcond_i3_reg_936 == 1'd0))) begin
        j_i3_reg_395 <= j_13_reg_940;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (exitcond_i8_fu_644_p2 == 1'd0))) begin
        j_i7_reg_362 <= j_10_fu_650_p2;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        j_i7_reg_362 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (exitcond_i_fu_603_p2 == 1'd0))) begin
        j_i_reg_351 <= j_fu_609_p2;
    end else if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        j_i_reg_351 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_reg_pp1_iter1_e3_addr_reg_828 <= e3_addr_reg_828;
        ap_reg_pp1_iter1_exitcond_i_reg_819 <= exitcond_i_reg_819;
        exitcond_i_reg_819 <= exitcond_i_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        ap_reg_pp1_iter2_e3_addr_reg_828 <= ap_reg_pp1_iter1_e3_addr_reg_828;
        ap_reg_pp1_iter2_exitcond_i_reg_819 <= ap_reg_pp1_iter1_exitcond_i_reg_819;
        ap_reg_pp1_iter3_e3_addr_reg_828 <= ap_reg_pp1_iter2_e3_addr_reg_828;
        ap_reg_pp1_iter3_exitcond_i_reg_819 <= ap_reg_pp1_iter2_exitcond_i_reg_819;
        ap_reg_pp1_iter4_e3_addr_reg_828 <= ap_reg_pp1_iter3_e3_addr_reg_828;
        ap_reg_pp1_iter4_exitcond_i_reg_819 <= ap_reg_pp1_iter3_exitcond_i_reg_819;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        ap_reg_pp2_iter1_exitcond_i8_reg_849 <= exitcond_i8_reg_849;
        ap_reg_pp2_iter1_tmp_i9_reg_858[8 : 0] <= tmp_i9_reg_858[8 : 0];
        exitcond_i8_reg_849 <= exitcond_i8_fu_644_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        ap_reg_pp2_iter2_exitcond_i8_reg_849 <= ap_reg_pp2_iter1_exitcond_i8_reg_849;
        ap_reg_pp2_iter2_tmp_i9_reg_858[8 : 0] <= ap_reg_pp2_iter1_tmp_i9_reg_858[8 : 0];
        ap_reg_pp2_iter3_exitcond_i8_reg_849 <= ap_reg_pp2_iter2_exitcond_i8_reg_849;
        ap_reg_pp2_iter3_tmp_i9_reg_858[8 : 0] <= ap_reg_pp2_iter2_tmp_i9_reg_858[8 : 0];
        ap_reg_pp2_iter4_exitcond_i8_reg_849 <= ap_reg_pp2_iter3_exitcond_i8_reg_849;
        ap_reg_pp2_iter4_tmp_i9_reg_858[8 : 0] <= ap_reg_pp2_iter3_tmp_i9_reg_858[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_reg_pp3_iter1_c1_addr_3_reg_892 <= c1_addr_3_reg_892;
        ap_reg_pp3_iter1_exitcond_i1_reg_878 <= exitcond_i1_reg_878;
        ap_reg_pp3_iter2_c1_addr_3_reg_892 <= ap_reg_pp3_iter1_c1_addr_3_reg_892;
        ap_reg_pp3_iter2_exitcond_i1_reg_878 <= ap_reg_pp3_iter1_exitcond_i1_reg_878;
        exitcond_i1_reg_878 <= exitcond_i1_fu_675_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        ap_reg_pp4_iter1_exitcond_i2_reg_907 <= exitcond_i2_reg_907;
        ap_reg_pp4_iter1_tmp_i2_reg_916[8 : 0] <= tmp_i2_reg_916[8 : 0];
        exitcond_i2_reg_907 <= exitcond_i2_fu_716_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp4_stage0_11001)) begin
        ap_reg_pp4_iter2_exitcond_i2_reg_907 <= ap_reg_pp4_iter1_exitcond_i2_reg_907;
        ap_reg_pp4_iter2_tmp_i2_reg_916[8 : 0] <= ap_reg_pp4_iter1_tmp_i2_reg_916[8 : 0];
        ap_reg_pp4_iter3_exitcond_i2_reg_907 <= ap_reg_pp4_iter2_exitcond_i2_reg_907;
        ap_reg_pp4_iter3_tmp_i2_reg_916[8 : 0] <= ap_reg_pp4_iter2_tmp_i2_reg_916[8 : 0];
        ap_reg_pp4_iter4_exitcond_i2_reg_907 <= ap_reg_pp4_iter3_exitcond_i2_reg_907;
        ap_reg_pp4_iter4_tmp_i2_reg_916[8 : 0] <= ap_reg_pp4_iter3_tmp_i2_reg_916[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        ap_reg_pp5_iter1_c2_addr_1_reg_950 <= c2_addr_1_reg_950;
        ap_reg_pp5_iter1_exitcond_i3_reg_936 <= exitcond_i3_reg_936;
        ap_reg_pp5_iter2_c2_addr_1_reg_950 <= ap_reg_pp5_iter1_c2_addr_1_reg_950;
        ap_reg_pp5_iter2_exitcond_i3_reg_936 <= ap_reg_pp5_iter1_exitcond_i3_reg_936;
        exitcond_i3_reg_936 <= exitcond_i3_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (exitcond_i1_fu_675_p2 == 1'd0))) begin
        c1_addr_3_reg_892 <= tmp_i1_94_fu_687_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (1'b1 == ap_CS_fsm_pp5_stage0) & (exitcond_i3_fu_747_p2 == 1'd0))) begin
        c2_addr_1_reg_950 <= tmp_i3_99_fu_759_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (exitcond_i_fu_603_p2 == 1'd0))) begin
        e3_addr_reg_828 <= tmp_i_fu_615_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_reg_800 <= exitcond_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        j_11_reg_882 <= j_11_fu_681_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        j_13_reg_940 <= j_13_fu_753_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0) & (exitcond_i2_reg_907 == 1'd0))) begin
        tmp_173_i1_reg_931 <= tmp_173_i1_fu_794_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (exitcond_i8_reg_849 == 1'd0))) begin
        tmp_173_i_reg_873 <= tmp_173_i_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (exitcond_i_reg_819 == 1'd0))) begin
        tmp_176_i_reg_839 <= tmp_176_i_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1) & (exitcond_i1_reg_878 == 1'd0))) begin
        tmp_177_i1_reg_897 <= tmp_177_i1_fu_701_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage1_11001) & (1'b1 == ap_CS_fsm_pp5_stage1) & (exitcond_i3_reg_936 == 1'd0))) begin
        tmp_177_i2_reg_955 <= tmp_177_i2_fu_773_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0) & (exitcond_i2_fu_716_p2 == 1'd0))) begin
        tmp_i2_reg_916[8 : 0] <= tmp_i2_fu_728_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (exitcond_i8_fu_644_p2 == 1'd0))) begin
        tmp_i9_reg_858[8 : 0] <= tmp_i9_fu_656_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_809[8 : 0] <= tmp_fu_579_p1[8 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_fu_567_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_603_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i8_fu_644_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state18 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state18 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i1_fu_675_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state25 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state25 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i2_fu_716_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state32 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state32 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i3_fu_747_p2 == 1'd1)) begin
        ap_condition_pp5_exit_iter0_state39 = 1'b1;
    end else begin
        ap_condition_pp5_exit_iter0_state39 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state46) & (1'b0 == ap_block_state46_on_subcall_done)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter5 == 1'b0) & (ap_enable_reg_pp4_iter4 == 1'b0) & (ap_enable_reg_pp4_iter3 == 1'b0) & (ap_enable_reg_pp4_iter2 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b0) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter0 == 1'b0))) begin
        ap_idle_pp5 = 1'b1;
    end else begin
        ap_idle_pp5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (exitcond_i1_reg_878 == 1'd0))) begin
        ap_phi_mux_j_i1_phi_fu_377_p4 = j_11_reg_882;
    end else begin
        ap_phi_mux_j_i1_phi_fu_377_p4 = j_i1_reg_373;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (exitcond_i3_reg_936 == 1'd0))) begin
        ap_phi_mux_j_i3_phi_fu_399_p4 = j_13_reg_940;
    end else begin
        ap_phi_mux_j_i3_phi_fu_399_p4 = j_i3_reg_395;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) & (1'b0 == ap_block_state46_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1) & (1'b0 == ap_block_pp3_stage1))) begin
        c1_address0 = ap_reg_pp3_iter2_c1_addr_3_reg_892;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        c1_address0 = tmp_i1_94_fu_687_p1;
    end else if (((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        c1_address0 = ap_reg_pp2_iter4_tmp_i9_reg_858;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c1_address0 = grp_rearrange2_fu_555_a_address0;
    end else begin
        c1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1)) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        c1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c1_ce0 = grp_rearrange2_fu_555_a_ce0;
    end else begin
        c1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1) & (1'b0 == ap_block_pp3_stage1))) begin
        c1_d0 = p_trunc8_ext_fu_711_p1;
    end else if (((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        c1_d0 = p_trunc7_ext_fu_670_p1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c1_d0 = grp_rearrange2_fu_555_a_d0;
    end else begin
        c1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1) & (ap_reg_pp3_iter2_exitcond_i1_reg_878 == 1'd0)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_reg_pp2_iter4_exitcond_i8_reg_849 == 1'd0)))) begin
        c1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c1_we0 = grp_rearrange2_fu_555_a_we0;
    end else begin
        c1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1) & (1'b0 == ap_block_pp5_stage1))) begin
        c2_address0 = ap_reg_pp5_iter2_c2_addr_1_reg_950;
    end else if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        c2_address0 = tmp_i3_99_fu_759_p1;
    end else if (((ap_enable_reg_pp4_iter5 == 1'b1) & (1'b0 == ap_block_pp4_stage0))) begin
        c2_address0 = ap_reg_pp4_iter4_tmp_i2_reg_916;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c2_address0 = grp_rearrange2_fu_561_a_address0;
    end else begin
        c2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage1_11001) & (ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1)) | ((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter5 == 1'b1)))) begin
        c2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c2_ce0 = grp_rearrange2_fu_561_a_ce0;
    end else begin
        c2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1) & (1'b0 == ap_block_pp5_stage1))) begin
        c2_d0 = p_trunc10_ext_fu_783_p1;
    end else if (((ap_enable_reg_pp4_iter5 == 1'b1) & (1'b0 == ap_block_pp4_stage0))) begin
        c2_d0 = p_trunc9_ext_fu_742_p1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c2_d0 = grp_rearrange2_fu_561_a_d0;
    end else begin
        c2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage1_11001) & (ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1) & (ap_reg_pp5_iter2_exitcond_i3_reg_936 == 1'd0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter5 == 1'b1) & (ap_reg_pp4_iter4_exitcond_i2_reg_907 == 1'd0)))) begin
        c2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        c2_we0 = grp_rearrange2_fu_561_a_we0;
    end else begin
        c2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0))) begin
        e1_address0 = tmp_i2_fu_728_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        e1_address0 = tmp_i9_fu_656_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_address0 = grp_fwd_ntt2_fu_529_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e1_address0 = grp_knuth_yao2_fu_406_a_address0;
    end else begin
        e1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        e1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_ce0 = grp_fwd_ntt2_fu_529_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e1_ce0 = grp_knuth_yao2_fu_406_a_ce0;
    end else begin
        e1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_ce1 = grp_fwd_ntt2_fu_529_a_ce1;
    end else begin
        e1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_d0 = grp_fwd_ntt2_fu_529_a_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e1_d0 = grp_knuth_yao2_fu_406_a_d0;
    end else begin
        e1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_we0 = grp_fwd_ntt2_fu_529_a_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e1_we0 = grp_knuth_yao2_fu_406_a_we0;
    end else begin
        e1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e1_we1 = grp_fwd_ntt2_fu_529_a_we1;
    end else begin
        e1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        e2_address0 = tmp_i1_94_fu_687_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_address0 = grp_fwd_ntt2_fu_536_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        e2_address0 = grp_knuth_yao2_fu_406_a_address0;
    end else begin
        e2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        e2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_ce0 = grp_fwd_ntt2_fu_536_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        e2_ce0 = grp_knuth_yao2_fu_406_a_ce0;
    end else begin
        e2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_ce1 = grp_fwd_ntt2_fu_536_a_ce1;
    end else begin
        e2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_d0 = grp_fwd_ntt2_fu_536_a_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        e2_d0 = grp_knuth_yao2_fu_406_a_d0;
    end else begin
        e2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_we0 = grp_fwd_ntt2_fu_536_a_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        e2_we0 = grp_knuth_yao2_fu_406_a_we0;
    end else begin
        e2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e2_we1 = grp_fwd_ntt2_fu_536_a_we1;
    end else begin
        e2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        e3_address0 = tmp_i3_99_fu_759_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        e3_address0 = tmp_i_fu_615_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_address0 = grp_fwd_ntt2_fu_543_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e3_address0 = grp_knuth_yao2_fu_406_a_address0;
    end else begin
        e3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        e3_address1 = ap_reg_pp1_iter4_e3_addr_reg_828;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_address1 = grp_fwd_ntt2_fu_543_a_address1;
    end else begin
        e3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        e3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_ce0 = grp_fwd_ntt2_fu_543_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e3_ce0 = grp_knuth_yao2_fu_406_a_ce0;
    end else begin
        e3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        e3_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_ce1 = grp_fwd_ntt2_fu_543_a_ce1;
    end else begin
        e3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_d0 = grp_fwd_ntt2_fu_543_a_d0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e3_d0 = grp_knuth_yao2_fu_406_a_d0;
    end else begin
        e3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        e3_d1 = p_trunc_ext_fu_639_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_d1 = grp_fwd_ntt2_fu_543_a_d1;
    end else begin
        e3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_we0 = grp_fwd_ntt2_fu_543_a_we0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e3_we0 = grp_knuth_yao2_fu_406_a_we0;
    end else begin
        e3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_reg_pp1_iter4_exitcond_i_reg_819 == 1'd0))) begin
        e3_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        e3_we1 = grp_fwd_ntt2_fu_543_a_we1;
    end else begin
        e3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        encoded_m_address0 = tmp_i_fu_615_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        encoded_m_address0 = tmp_reg_809;
    end else begin
        encoded_m_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        encoded_m_ce0 = 1'b1;
    end else begin
        encoded_m_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        encoded_m_we0 = 1'b1;
    end else begin
        encoded_m_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage1_11001) & (1'b1 == ap_CS_fsm_pp5_stage1)) | ((1'b0 == ap_block_pp5_stage0_11001) & (1'b1 == ap_CS_fsm_pp5_stage0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1)) | ((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        grp_mod_r_fu_550_ap_ce = 1'b1;
    end else begin
        grp_mod_r_fu_550_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (exitcond_i3_reg_936 == 1'd0))) begin
        grp_mod_r_fu_550_x = tmp_177_i2_cast_fu_779_p1;
    end else if (((ap_enable_reg_pp4_iter2 == 1'b1) & (1'b0 == ap_block_pp4_stage0) & (ap_reg_pp4_iter1_exitcond_i2_reg_907 == 1'd0))) begin
        grp_mod_r_fu_550_x = tmp_173_i1_reg_931;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (exitcond_i1_reg_878 == 1'd0))) begin
        grp_mod_r_fu_550_x = tmp_177_i1_cast_fu_707_p1;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (ap_reg_pp2_iter1_exitcond_i8_reg_849 == 1'd0))) begin
        grp_mod_r_fu_550_x = tmp_173_i_reg_873;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (ap_reg_pp1_iter1_exitcond_i_reg_819 == 1'd0))) begin
        grp_mod_r_fu_550_x = tmp_176_i_cast_fu_635_p1;
    end else begin
        grp_mod_r_fu_550_x = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_ce0 = 1'b1;
    end else begin
        m_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        p_ce0 = 1'b1;
    end else begin
        p_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_fu_567_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_fu_567_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_knuth_yao2_fu_406_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_i_fu_603_p2 == 1'd1)) & ~((ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (exitcond_i_fu_603_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (exitcond_i8_fu_644_p2 == 1'd1)) & ~((ap_enable_reg_pp2_iter4 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((ap_enable_reg_pp2_iter4 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter5 == 1'b1)) | ((ap_enable_reg_pp2_iter1 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (exitcond_i8_fu_644_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((ap_enable_reg_pp3_iter1 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone) & (exitcond_i1_fu_675_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone) & (exitcond_i1_fu_675_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_pp3_stage1 : begin
            if ((~((1'b0 == ap_block_pp3_stage1_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1)) & (1'b0 == ap_block_pp3_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((1'b0 == ap_block_pp3_stage1_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_pp4_stage0;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if ((~((ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (exitcond_i2_fu_716_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)) & ~((ap_enable_reg_pp4_iter4 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if ((((ap_enable_reg_pp4_iter4 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter5 == 1'b1)) | ((ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (exitcond_i2_fu_716_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_pp5_stage0;
        end
        ap_ST_fsm_pp5_stage0 : begin
            if ((~((ap_enable_reg_pp5_iter1 == 1'b0) & (1'b0 == ap_block_pp5_stage0_subdone) & (exitcond_i3_fu_747_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1)) & (1'b0 == ap_block_pp5_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage1;
            end else if (((ap_enable_reg_pp5_iter1 == 1'b0) & (1'b0 == ap_block_pp5_stage0_subdone) & (exitcond_i3_fu_747_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end
        end
        ap_ST_fsm_pp5_stage1 : begin
            if ((~((1'b0 == ap_block_pp5_stage1_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1)) & (1'b0 == ap_block_pp5_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end else if (((1'b0 == ap_block_pp5_stage1_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage1;
            end
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            if (((1'b1 == ap_CS_fsm_state46) & (1'b0 == ap_block_state46_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = tmp_i9_fu_656_p1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp3_stage1 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp5_stage0 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp5_stage1 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_on_subcall_done = ((grp_fwd_ntt2_fu_543_ap_done == 1'b0) | (grp_fwd_ntt2_fu_536_ap_done == 1'b0) | (grp_fwd_ntt2_fu_529_ap_done == 1'b0));
end

assign ap_block_state18_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp3_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp3_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp3_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp4_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp4_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp4_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp4_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp4_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp5_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp5_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp5_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp5_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp5_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp5_stage1_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state46_on_subcall_done = ((grp_rearrange2_fu_561_ap_done == 1'b0) | (grp_rearrange2_fu_555_ap_done == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_enable_pp5 = (ap_idle_pp5 ^ 1'b1);

assign encoded_m_d0 = (tmp_158_fu_584_p2 - tmp_159_fu_590_p2);

assign exitcond_fu_567_p2 = ((i_reg_340 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i1_fu_675_p2 = ((ap_phi_mux_j_i1_phi_fu_377_p4 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i2_fu_716_p2 = ((j_i2_reg_384 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i3_fu_747_p2 = ((ap_phi_mux_j_i3_phi_fu_399_p4 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i8_fu_644_p2 = ((j_i7_reg_362 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_i_fu_603_p2 = ((j_i_reg_351 == 9'd256) ? 1'b1 : 1'b0);

assign grp_fwd_ntt2_fu_529_ap_start = ap_reg_grp_fwd_ntt2_fu_529_ap_start;

assign grp_fwd_ntt2_fu_536_ap_start = ap_reg_grp_fwd_ntt2_fu_536_ap_start;

assign grp_fwd_ntt2_fu_543_ap_start = ap_reg_grp_fwd_ntt2_fu_543_ap_start;

assign grp_knuth_yao2_fu_406_ap_start = ap_reg_grp_knuth_yao2_fu_406_ap_start;

assign grp_rearrange2_fu_555_ap_start = ap_reg_grp_rearrange2_fu_555_ap_start;

assign grp_rearrange2_fu_561_ap_start = ap_reg_grp_rearrange2_fu_561_ap_start;

assign i_5_fu_573_p2 = (i_reg_340 + 9'd1);

assign j_10_fu_650_p2 = (j_i7_reg_362 + 9'd1);

assign j_11_fu_681_p2 = (ap_phi_mux_j_i1_phi_fu_377_p4 + 9'd1);

assign j_12_fu_722_p2 = (j_i2_reg_384 + 9'd1);

assign j_13_fu_753_p2 = (ap_phi_mux_j_i3_phi_fu_399_p4 + 9'd1);

assign j_fu_609_p2 = (j_i_reg_351 + 9'd1);

assign m_address0 = tmp_fu_579_p1;

assign p_address0 = tmp_i2_fu_728_p1;

assign p_trunc10_ext_fu_783_p1 = $signed(grp_mod_r_fu_550_ap_return);

assign p_trunc7_ext_fu_670_p1 = $signed(grp_mod_r_fu_550_ap_return);

assign p_trunc8_ext_fu_711_p1 = $signed(grp_mod_r_fu_550_ap_return);

assign p_trunc9_ext_fu_742_p1 = $signed(grp_mod_r_fu_550_ap_return);

assign p_trunc_ext_fu_639_p1 = $signed(grp_mod_r_fu_550_ap_return);

assign tmp_158_fu_584_p2 = m_q0 << 16'd12;

assign tmp_159_fu_590_p2 = m_q0 << 16'd8;

assign tmp_173_i1_fu_794_p0 = tmp_173_i1_fu_794_p00;

assign tmp_173_i1_fu_794_p00 = p_q0;

assign tmp_173_i1_fu_794_p1 = tmp_173_i1_fu_794_p10;

assign tmp_173_i1_fu_794_p10 = e1_q0;

assign tmp_173_i_fu_788_p0 = tmp_173_i_fu_788_p00;

assign tmp_173_i_fu_788_p00 = a_q0;

assign tmp_173_i_fu_788_p1 = tmp_173_i_fu_788_p10;

assign tmp_173_i_fu_788_p10 = e1_q0;

assign tmp_175_i_cast_fu_625_p1 = encoded_m_q0;

assign tmp_176_i1_cast_fu_697_p1 = c1_q0;

assign tmp_176_i2_cast_fu_769_p1 = c2_q0;

assign tmp_176_i_cast_fu_635_p1 = tmp_176_i_reg_839;

assign tmp_176_i_fu_629_p2 = (tmp_i_cast_fu_621_p1 + tmp_175_i_cast_fu_625_p1);

assign tmp_177_i1_cast_fu_707_p1 = tmp_177_i1_reg_897;

assign tmp_177_i1_fu_701_p2 = (tmp_i2_cast_fu_693_p1 + tmp_176_i1_cast_fu_697_p1);

assign tmp_177_i2_cast_fu_779_p1 = tmp_177_i2_reg_955;

assign tmp_177_i2_fu_773_p2 = (tmp_i4_cast_fu_765_p1 + tmp_176_i2_cast_fu_769_p1);

assign tmp_fu_579_p1 = i_reg_340;

assign tmp_i1_94_fu_687_p1 = ap_phi_mux_j_i1_phi_fu_377_p4;

assign tmp_i2_cast_fu_693_p1 = e2_q0;

assign tmp_i2_fu_728_p1 = j_i2_reg_384;

assign tmp_i3_99_fu_759_p1 = ap_phi_mux_j_i3_phi_fu_399_p4;

assign tmp_i4_cast_fu_765_p1 = e3_q0;

assign tmp_i9_fu_656_p1 = j_i7_reg_362;

assign tmp_i_cast_fu_621_p1 = e3_q0;

assign tmp_i_fu_615_p1 = j_i_reg_351;

always @ (posedge ap_clk) begin
    tmp_reg_809[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_i9_reg_858[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp2_iter1_tmp_i9_reg_858[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp2_iter2_tmp_i9_reg_858[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp2_iter3_tmp_i9_reg_858[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp2_iter4_tmp_i9_reg_858[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_i2_reg_916[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp4_iter1_tmp_i2_reg_916[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp4_iter2_tmp_i2_reg_916[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp4_iter3_tmp_i2_reg_916[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    ap_reg_pp4_iter4_tmp_i2_reg_916[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //RLWE_enc2
