-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity knuth_yao_single_Xh4_rom is 
    generic(
             dwidth     : integer := 1; 
             awidth     : integer := 7; 
             mem_size    : integer := 109
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of knuth_yao_single_Xh4_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 3=> "0", 4 => "1", 5 to 6=> "0", 7 => "1", 8 => "0", 9 to 10=> "1", 11 => "0", 
    12 => "1", 13 => "0", 14 to 15=> "1", 16 to 17=> "0", 18 to 19=> "1", 20 to 21=> "0", 22 to 23=> "1", 
    24 => "0", 25 to 27=> "1", 28 => "0", 29 => "1", 30 to 33=> "0", 34 => "1", 35 to 36=> "0", 
    37 to 39=> "1", 40 => "0", 41 => "1", 42 to 43=> "0", 44 to 45=> "1", 46 to 48=> "0", 49 => "1", 
    50 to 51=> "0", 52 to 54=> "1", 55 => "0", 56 => "1", 57 to 59=> "0", 60 => "1", 61 => "0", 
    62 to 64=> "1", 65 => "0", 66 to 69=> "1", 70 to 72=> "0", 73 to 78=> "1", 79 to 81=> "0", 82 to 84=> "1", 
    85 to 88=> "0", 89 => "1", 90 => "0", 91 => "1", 92 => "0", 93 to 100=> "1", 101 => "0", 
    102 => "1", 103 to 105=> "0", 106 => "1", 107 => "0", 108 => "1" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity knuth_yao_single_Xh4 is
    generic (
        DataWidth : INTEGER := 1;
        AddressRange : INTEGER := 109;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of knuth_yao_single_Xh4 is
    component knuth_yao_single_Xh4_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    knuth_yao_single_Xh4_rom_U :  component knuth_yao_single_Xh4_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


