-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity knuth_yao_single_Rg6_rom is 
    generic(
             dwidth     : integer := 1; 
             awidth     : integer := 7; 
             mem_size    : integer := 109
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of knuth_yao_single_Rg6_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 8=> "0", 9 => "1", 10 => "0", 11 to 14=> "1", 15 => "0", 16 to 17=> "1", 18 to 19=> "0", 
    20 => "1", 21 => "0", 22 to 23=> "1", 24 => "0", 25 to 26=> "1", 27 => "0", 28 to 30=> "1", 
    31 => "0", 32 => "1", 33 => "0", 34 => "1", 35 => "0", 36 => "1", 37 => "0", 
    38 => "1", 39 to 40=> "0", 41 to 44=> "1", 45 to 46=> "0", 47 to 48=> "1", 49 to 55=> "0", 56 to 57=> "1", 
    58 to 62=> "0", 63 to 69=> "1", 70 to 72=> "0", 73 => "1", 74 => "0", 75 => "1", 76 to 77=> "0", 
    78 => "1", 79 to 82=> "0", 83 to 85=> "1", 86 to 88=> "0", 89 => "1", 90 => "0", 91 to 92=> "1", 
    93 => "0", 94 to 95=> "1", 96 => "0", 97 => "1", 98 to 99=> "0", 100 => "1", 101 => "0", 
    102 to 104=> "1", 105 to 107=> "0", 108 => "1" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity knuth_yao_single_Rg6 is
    generic (
        DataWidth : INTEGER := 1;
        AddressRange : INTEGER := 109;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of knuth_yao_single_Rg6 is
    component knuth_yao_single_Rg6_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    knuth_yao_single_Rg6_rom_U :  component knuth_yao_single_Rg6_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


